spring:
  application:
    name: order-service


# config for oauth2 server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks

#config datasource
  datasource:
    url: jdbc:postgresql://localhost:5992/order_db
    username: order
    password: order
    driver-class-name: org.postgresql.Driver

# config for ddl
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# config for loan balance
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - product-service

# config eureka client to register
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30

  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    ip-address: 127.0.0.1

server:
  port: 9003
